# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: benchun
name: benchun.net
description: Teacher, DJ, Citizen
url: http://benchun.net
github_username:  benchun

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from

exclude:
  - projects.md
  - speaking.md
